'1 - Pepperoni (+ R$ 15,00)\n '
      '(Molho de Tomate - Mussarela - Pepperoni)\n'
      '\n'
      '2 - Quatro Queijos (+ 15,00)\n(Molho de Tomate - Mussarela - Parmesão - Provolone - Gorgonzola)\n'
      '\n'
      '3 - Frango com Catupiry (+ R$ 10,00)\n(Molho de Tomate - Mussarela - Frango Desfiado - Catupiry - Cebola)\n'
      '\n'
      '4 - Calabresa (+ R$ 5,00)\n(Molho de Tomate - Mussarela - Calabresa - Cebola)\n'
      '\n'
      '5 - Marguerita (+ R$ 5,00)\n(Molho de Tomate - Mussarela - Tomate - Mangericão)\n'
      '\n'
      '0 - Nenhum, desisti voltarei outra hora!\n'
      '\n'
      'Digite aqui o número: '